version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: playlist-postgres
    environment:
      POSTGRES_DB: playlist_db
      POSTGRES_USER: playlist_user
      POSTGRES_PASSWORD: playlist_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: